name: generate animation

on:
  # 每天凌晨 0 点自动运行
  schedule:
    - cron: "0 0 * * *"

  # 允许手动触发工作流
  workflow_dispatch:

  # 在 main 分支上有 push 操作时触发
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # 检出当前仓库的代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 从 GitHub 用户的贡献图生成贪吃蛇游戏 SVG 动画，输出到指定路径
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: xiaojueshi
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 将 <build_dir> 的内容推送到目标分支
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
